app = 'emf-beer'
primary_region = 'lhr'

[build]

[env]
  UDP_BIND_ADDRESS = 'fly-global-services'
  PUBLIC_IPV4 = '37.16.1.216'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[services]]
  protocol = 'udp'
  internal_port = 5080
  [[services.ports]]
    port = 5080

[[services]]
  protocol = 'udp'
  internal_port = 4000
  [[services.ports]]
    port = 4000

[[services]]
  protocol = 'udp'
  internal_port = 4001
  [[services.ports]]
    port = 4001

[[services]]
  protocol = 'udp'
  internal_port = 4002
  [[services.ports]]
    port = 4002

[[services]]
  protocol = 'udp'
  internal_port = 4003
  [[services.ports]]
    port = 4003

[[services]]
  protocol = 'udp'
  internal_port = 4004
  [[services.ports]]
    port = 4004

[[services]]
  protocol = 'udp'
  internal_port = 4005
  [[services.ports]]
    port = 4005

[[services]]
  protocol = 'udp'
  internal_port = 4006
  [[services.ports]]
    port = 4006

[[services]]
  protocol = 'udp'
  internal_port = 4007
  [[services.ports]]
    port = 4007

[[vm]]
  memory = '2gb'
  cpus = 1
  memory_mb = 2048
  cpu_kind = 'shared'
  processes = ['app']
  size = 'shared-cpu-1x'
